name: Daily Commit

on:
  schedule:
    # Runs daily at 09:30 UTC (adjust hours/minutes if needed)
    - cron: '30 9 * * *'

jobs:
  commit_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Add a commit (23f2002677@ds.study.iitm.ac.in)
        run: |
          echo "Daily update $(date)" >> daily_update.txt
          git config user.name "GitHub Action"
          git config user.email "23f2002677@ds.study.iitm.ac.in"
          git add daily_update.txt
          git commit -m "Daily commit from GitHub Action"
          git push
